### ISSUE TITLE
How to install bro on Ubuntu 18.04?

### ISSUE THREAD

**Issue by orschiro** [hubsmoke/bro#72]
Did `apt install ruby`. Then:

```
orschiro@x230:~$ gem install bropages
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
```
```
orschiro@x230:~$ sudo gem install bropages
Building native extensions.  This could take a while...
ERROR:  Error installing bropages:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.4/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20171123-20103-ihn6s4.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.4/gem_make.out
```

**Comment by gitcomrade** [comment]
Sounds like you might need the dev package installed.  Try "apt install ruby2.3-dev" and then rerun your gem install.

**Comment by orschiro** [comment]
@gitcomrade thanks for your help! Still the same issue:

```
orschiro@x230:~$ sudo apt install ruby2.3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ruby2.3-dev is already the newest version (2.3.5-1ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

orschiro@x230:~$ sudo gem install bropages
Building native extensions.  This could take a while...
ERROR:  Error installing bropages:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.4/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20171130-31713-13agjiv.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /usr/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /usr/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.4/gem_make.out
```

**Comment by gitcomrade** [comment]
Sorry for the delay getting back to you.  Just reproduced this on Ubuntu 17.10 and found a fix.  Bropages has missing dependencies for ruby-unf and ruby-unf-ext.  You can install them using "sudo apt install ruby-unf" and this will give you both packages.  

I also installed ruby-dev beforehand, so if ruby-unf doesn't fix it try adding ruby-dev too.  The error line "current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.4/ext/unf_ext" was the clue for this solution.

**Comment by orschiro** [comment]
Thank you! So, this should be the total list of packages one needs to install: 

    $ sudo apt install ruby ruby2.3-dev ruby-unf ruby-dev

**Comment by KANGOD** [comment]
Hello Contributors, it would be very appreciate if you include the dependencies inside the `Install` section of  README.md . http://bropages.org just said `gem install bropages`, for one who never have been to the Ruby world, it would be `apt install gem` then find out that it's not the `gem`. Including a install guide in README.md would be extremely helpful.
