### ISSUE TITLE
error on Mac: The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)

### ISSUE THREAD

**Issue by sinepgnol** [hubsmoke/bro#80]
I'm running macOS Big Sur 11.3.1 and I installed bropages successfuly. Upon running it I always get the following error message:

`% bro wget              
/Users/martin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328:in `const_get'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328:in `block in <module:AskForClass>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:326:in `map'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:326:in `<module:AskForClass>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:322:in `<module:UI>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:13:in `<module:Commander>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:4:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander.rb:27:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/import.rb:2:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bropages-0.1.0/lib/bro.rb:14:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bropages-0.1.0/bin/bro:2:in `<top (required)>'
	from /Users/martin/.rbenv/versions/3.0.0/bin/bro:23:in `load'
	from /Users/martin/.rbenv/versions/3.0.0/bin/bro:23:in `<main>'
<internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328:in `const_get'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:328:in `block in <module:AskForClass>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:326:in `map'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:326:in `<module:AskForClass>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:322:in `<module:UI>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:13:in `<module:Commander>'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/user_interaction.rb:4:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander.rb:27:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/commander-4.1.5/lib/commander/import.rb:2:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bropages-0.1.0/lib/bro.rb:14:in `<top (required)>'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/martin/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/martin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bropages-0.1.0/bin/bro:2:in `<top (required)>'
	from /Users/martin/.rbenv/versions/3.0.0/bin/bro:23:in `load'
	from /Users/martin/.rbenv/versions/3.0.0/bin/bro:23:in `<main>'`

I remember it used to run ok on Catalina.

**Comment by TexaCaliCoder** [comment]
Same issue here.

**Comment by sinepgnol** [comment]
> Same issue here.

Have you solved it somehow?
